# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jun Yong Eom
title: This is a demo page. Please don't be serious.
email: TBD
website: https://junyongeom.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  junyongeom
# kaggle_username:  liketherain
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# 추가 할 수 있는 링크임 아무거나 
# additional_links:
# - title: itsgoingto.be
  # icon: fas fa-globe
  # url: https://www.itsgoingto.be

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Jun Yong Eom can be a fascinating companion. 

  He possesses a **tta-leung-e** *semi-annual ticket* and **1st class** *ordinary driver's license*.

  He is most skilled in: <mark>Radio Resource management</mark> and <mark>Drinking</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is the greatest project ever created.
        description: | # this will include new lines to allow paragraphs
          He started this project for <mark>fun</mark>. It is widely known in communication societies that he dedicated his whole life as an ***Ttubeokyee***
          in *Republic of Korea*.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Republic of Korea Army
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: March 2018 - June 2020
        quote: >
          Solving 21st century problems by diging holes.
        description: | # this will include new lines to allow paragraphs
            He is **Goon Pil**.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Swimming
        caption: 2022 - present
        sub_title: Butterfly stroke is hard to learn
        quote: >
          I think he needs more education...
        description: | # this will include new lines to allow paragraphs
          Eagerly working guy.

          He spent a lot of his free time as a *Kaggler*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and researches some of my other interests and hobbies are:
      - Kickboxing
      - Swimming
      - Cycling
      - [Watching the speaking orca..!](https://www.youtube.com/watch?v=uAiF9cBTADc)


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
